# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_pb2 as server__pb2


class TestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/test.Test/SayHello',
        request_serializer=server__pb2.HelloRequest.SerializeToString,
        response_deserializer=server__pb2.HelloReply.FromString,
        )
    self.Add = channel.unary_unary(
        '/test.Test/Add',
        request_serializer=server__pb2.Numbers.SerializeToString,
        response_deserializer=server__pb2.Sum.FromString,
        )


class TestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=server__pb2.HelloRequest.FromString,
          response_serializer=server__pb2.HelloReply.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=server__pb2.Numbers.FromString,
          response_serializer=server__pb2.Sum.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.Test', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
